config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'
  get 'game/index'
  get 'game/new'
  get 'game/show'
  get 'game/edit'

  get 'dictionary/index'
  get 'dictionary/new'
  get 'dictionary/show'
  get 'dictionary/edit'
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/dictionary_controller.rb
# frozen_string_literal: true

class DictionaryController < ApplicationController
  def index; end

  def new; end

  def show; end

  def edit; end
end

app/controllers/game_controller.rb
# frozen_string_literal: true

class GameController < ApplicationController
  def index; end

  def new; end

  def show; end

  def edit; end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/dictionary_helper.rb
# frozen_string_literal: true

module DictionaryHelper
end

app/helpers/game_helper.rb
# frozen_string_literal: true

module GameHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/dictionary/edit.html.erb
<h1>Dictionary#edit</h1>
<p>Find me in app/views/dictionary/edit.html.erb</p>

app/views/dictionary/index.html.erb
<h1>Dictionary#index</h1>
<p>Find me in app/views/dictionary/index.html.erb</p>

app/views/dictionary/new.html.erb
<h1>Dictionary#new</h1>
<p>Find me in app/views/dictionary/new.html.erb</p>

app/views/dictionary/show.html.erb
<h1>Dictionary#show</h1>
<p>Find me in app/views/dictionary/show.html.erb</p>

app/views/game/edit.html.erb
<h1>Game#edit</h1>
<p>Find me in app/views/game/edit.html.erb</p>

app/views/game/index.html.erb
<h1>Game#index</h1>
<p>Find me in app/views/game/index.html.erb</p>

app/views/game/new.html.erb
<h1>Game#new</h1>
<p>Find me in app/views/game/new.html.erb</p>

app/views/game/show.html.erb
<h1>Game#show</h1>
<p>Find me in app/views/game/show.html.erb</p>

app/views/home/_header.html.erb
<section class="hero is-info is-medium">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item">
            <p class="title">Dictionary Game</p>
          </a>
          <span class="navbar-burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            <a class="navbar-item">
              <%= link_to "Home", root_path %>
            </a>
            <a class="navbar-item">
              <%= link_to "Dictionary", dictionary_index_path %>
            </a>
            <a class="navbar-item">
              <%= link_to "Play Game", game_index_path %>
            </a>
          </div>
        </div>
      </div>
    </nav>
  </div>
</section>

app/views/home/index.html.erb
  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title">
        Welcome to the Dictionary Game
      </p>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dictionary Game</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  </head>
  <body>
    <%= render 'home/header' %> 
      <div class="container">
        <br>
        <%= yield %>
      </div>
  </body>
</html>